In [2]:
import numpy as np #numpy = numerical python

In [8]:
matrix_1 = np.array([[2,3],[4,5]]) #matrix syntax

In [6]:
print(matrix_1)

[[2 3]
 [4 5]]


In [7]:
matrix_1.shape

(2, 2)

In [13]:
matrix_2 = np.array([[2,3,4],[4,7,7],[6,9,4]])

In [14]:
print(matrix_2)

[[2 3 4]
 [4 7 7]
 [6 9 4]]


In [15]:
matrix_2.shape

(3, 3)

matrix with random values

In [18]:
a = np.random.rand(2,3)
print(a)

[[0.16682853 0.0080628  0.50468275]
 [0.01881727 0.88647532 0.5944538 ]]


In [19]:
#random matrix with int values
a = np.random.randint(100,size=(2,3)) #syntax (values less than no.,size=())
print(a)

[[88 75 60]
 [77 65 27]]


matrix with all zeroes

In [23]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
#all values are in float to convert it into int add dtype to it
a = np.zeros((2,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]]


matrix with all ones

In [25]:
a = np.ones((2,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


Identity Matrix

In [30]:
a = np.eye(4,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Transpose of matrix

In [32]:
#generate a random matrix
a = np.random.randint(100,size=(3,3))
print(a)

[[21  5 75]
 [27 33 18]
 [50 97 69]]


In [35]:
transpose_a = np.transpose(a)
print(transpose_a)

[[21 27 50]
 [ 5 33 97]
 [75 18 69]]
