importing numpy is important in mathematical operations

Matrix Addition 

In [2]:
import numpy as np

In [5]:
a = np.array([[2,3],[4,6]])
b = np.array([[3,4],[9,7]])
print(a)

[[2 3]
 [4 6]]


In [6]:
print(b)

[[3 4]
 [9 7]]


In [7]:
sum = a+b
print(sum)

[[ 5  7]
 [13 13]]


In [8]:
#second way

In [9]:
#taking random values this time
matrix_1 = np.random.randint(10, size=(2,2))
matrix_2 = np.random.randint(10, size=(2,2))
print(matrix_1)

[[8 9]
 [8 6]]


In [10]:
matrix_1.shape

(2, 2)

In [11]:
print(matrix_2)

[[2 4]
 [2 5]]


In [12]:
#another way of adding (2nd)
sum = np.add(matrix_1 , matrix_2)
print(sum)

[[10 13]
 [10 11]]


Matrix subtraction

In [13]:
a = np.array([[2,5],[6,7]])
b = np.array([[3,7],[7,9]])
print(a)

[[2 5]
 [6 7]]


In [14]:
print(b)

[[3 7]
 [7 9]]


In [15]:
diff = a-b
print(diff)

[[-1 -2]
 [-1 -2]]


In [16]:
#2nd way
a = np.random.randint(10, size = (2,2))
b = np.random.randint(10, size = (2,2))
print(a)

[[7 1]
 [3 2]]


In [17]:
print(b)

[[7 7]
 [8 7]]


In [19]:
diff = np.subtract(a,b)
print(diff)

[[ 0 -6]
 [-5 -5]]


In [20]:
a = np.random.randint(10, size = (2,2))
b = np.random.randint(10, size = (2,3))
print(a)

[[7 9]
 [1 0]]


In [21]:
print(b)

[[1 7 7]
 [6 2 0]]


In [22]:
sum = np.add(a,b)
print(sum)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [23]:
#because both matrices are'nt of same size (also applicable for differnece)

# multiplication of a scalar to matrix

In [24]:
a = 5
b = np.random.randint(10, size=(3,3))
print(b)

[[1 0 8]
 [3 4 5]
 [9 8 6]]


In [25]:
x = np.multiply(a,b)
print(x)

[[ 5  0 40]
 [15 20 25]
 [45 40 30]]


# multiplication of two matrices

In [27]:
a = np.random.randint(10, size= (3,4))
b = np.random.randint(10, size= (4,5))
#should follow the matrices multiplication rule i.e no. of coloumns of 1st matrix = no. of rows of 2nd matrix 
print(a)

[[9 2 1 9]
 [9 2 3 3]
 [8 2 1 6]]


In [28]:
print(b)

[[0 6 3 7 8]
 [2 0 6 6 6]
 [9 0 0 6 7]
 [4 6 0 6 6]]


In [29]:
a_multiplied_by_b = np.dot(a, b)
print(a_multiplied_by_b)

[[ 49 108  39 135 145]
 [ 43  72  39 111 123]
 [ 37  84  36 110 119]]


In [31]:
# order of above matrix = remaining row of 1st matrix i.e 3 and remaining coloumn of 2nd matrix i.e 5 (3,5)
a_multiplied_by_b.shape

(3, 5)

In [33]:
a = np.random.randint(10, size= (3,4))
b = np.random.randint(10, size= (6,5))
a_multiplied_by_b = np.dot(a, b)

ValueError: shapes (3,4) and (6,5) not aligned: 4 (dim 1) != 6 (dim 0)

In [34]:
#error as we did'nt followed matrices multiplication rule

# elementwise multiplication of matrices

In [35]:
a = np.random.randint(7, size=(3,3))
b = np.random.randint(7, size=(3,3))
#should have same shape
print(a)

[[6 4 6]
 [3 5 0]
 [6 1 0]]


In [36]:
print(b)

[[0 4 0]
 [1 6 3]
 [5 3 2]]


In [37]:
x = np.multiply(a, b)

In [38]:
print(x)

[[ 0 16  0]
 [ 3 30  0]
 [30  3  0]]
